name: My First Workflow

on: push

jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checking out the Repo
        uses: actions/checkout@v4

      - name: Welcome message
        run: echo "My first Github Actions Job"

      - name: List files
        run: ls -l

      - name: Read file
        run: cat fastapi_notes.md
